version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: "unless-stopped"
    env_file:
      - .env.mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: