[project]
name = "la_assistant"
version = "0.0.1"
description = "The language acquisition assistant app"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"